from collections.abc import Sequence
from typing import Any, final

@final
class Lanelet:
    def __new__(cls, /, left_bound: Sequence[Point], right_bound: Sequence[Point], id: int) -> Lanelet: ...
    def _addr(self, /) -> int: ...
    def _cr_capsule(self, /) -> Any: ...
    @property
    def id(self, /) -> int: ...
    @id.setter
    def id(self, /, val: int) -> None: ...

@final
class Point:
    def __new__(cls, /, x: float, y: float) -> Point: ...
    def _addr(self, /) -> int: ...
    def _cr_capsule(self, /) -> Any: ...
    @property
    def x(self, /) -> float: ...
    @x.setter
    def x(self, /, val: float) -> None: ...
    @property
    def y(self, /) -> float: ...
    @y.setter
    def y(self, /, val: float) -> None: ...

@final
class State:
    def __new__(cls, /, position: Point, orientation: float, velocity: float, time: int) -> State: ...
    def _addr(self, /) -> int: ...
    def _cr_capsule(self, /) -> Any: ...

def create_dummy_lanelet() -> Lanelet: ...
