from cr_core import Lanelet, Point, State
def bump_point_x(p: Point, dx: float) -> None: ...
def print_lanelet(l: Lanelet) -> int: ...
def print_point(p: Point) -> int: ...
def print_state(s: State) -> int: ...
