#pragma once

// Generated by cxx from src/bindings/cpp.rs — provides the shared
// cr_core::Point / State / Lanelet structs and rust::Vec.
#include "cr_core/src/bindings/cpp.rs.h"

namespace cr_core {

// Example C++ consumer of the shared structs (declared `extern "C++"` in the
// bridge). Averages all left+right bound points of a Lanelet.
Point lanelet_centroid(const Lanelet &lanelet);

} // namespace cr_core
